"""empty message

Revision ID: 06c430d07ab3
Revises: 862477883538
Create Date: 2022-11-11 15:23:00.861911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c430d07ab3'
down_revision = '862477883538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('on_test', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('mark', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('formation')
    op.add_column('subscription', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('subscription', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('subscription', sa.Column('subscription_date', sa.DateTime(), nullable=True))
    op.add_column('subscription', sa.Column('charges_paid', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'subscription', 'user', ['student_id'], ['id'])
    op.create_foreign_key(None, 'subscription', 'session', ['session_id'], ['id'])
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'charges_paid')
    op.drop_column('subscription', 'subscription_date')
    op.drop_column('subscription', 'session_id')
    op.drop_column('subscription', 'student_id')
    op.create_table('formation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='formation_pkey')
    )
    op.drop_table('note')
    op.drop_table('language_level')
    op.drop_table('level')
    op.drop_table('language')
    op.drop_table('category')
    # ### end Alembic commands ###
