"""empty message

Revision ID: 22a590b0a400
Revises: 1c0596b081ff
Create Date: 2022-11-23 10:19:18.157598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a590b0a400'
down_revision = '1c0596b081ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('label', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'label')
    # ### end Alembic commands ###
