"""empty message

Revision ID: 35f09fb60359
Revises: 3ac3aa4e72f4
Create Date: 2022-11-11 16:44:18.513355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f09fb60359'
down_revision = '3ac3aa4e72f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=10), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
