"""empty message

Revision ID: 3ac3aa4e72f4
Revises: 56eba4625882
Create Date: 2022-11-11 16:43:31.534962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac3aa4e72f4'
down_revision = '56eba4625882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('language_fk_session_id_fkey', 'language', type_='foreignkey')
    op.drop_column('language', 'fk_session_id')
    op.add_column('subscription', sa.Column('fk_language_id', sa.Integer(), nullable=True))
    op.add_column('subscription', sa.Column('fk_level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscription', 'level', ['fk_level_id'], ['id'])
    op.create_foreign_key(None, 'subscription', 'language', ['fk_language_id'], ['id'])
    op.add_column('user', sa.Column('fk_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'category', ['fk_category_id'], ['id'])
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'fk_category_id')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'fk_level_id')
    op.drop_column('subscription', 'fk_language_id')
    op.add_column('language', sa.Column('fk_session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('language_fk_session_id_fkey', 'language', 'session', ['fk_session_id'], ['id'])
    # ### end Alembic commands ###
