"""empty message

Revision ID: 44e91812d967
Revises: 894c35be3e4d
Create Date: 2022-11-11 17:55:27.410939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e91812d967'
down_revision = '894c35be3e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('course', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'is_disabled')
    op.drop_column('course', 'price')
    # ### end Alembic commands ###
