"""empty message

Revision ID: 56eba4625882
Revises: b2031df34953
Create Date: 2022-11-11 16:24:42.715102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56eba4625882'
down_revision = 'b2031df34953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('is_waiting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'is_waiting')
    # ### end Alembic commands ###
