"""empty message

Revision ID: 66437892ff1a
Revises: 22a590b0a400
Create Date: 2022-11-23 15:28:53.108504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66437892ff1a'
down_revision = '22a590b0a400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_level_id', sa.Integer(), nullable=True),
    sa.Column('fk_language_id', sa.Integer(), nullable=True),
    sa.Column('fk_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['fk_language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['fk_level_id'], ['level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_language')
    # ### end Alembic commands ###
