"""empty message

Revision ID: a172f54a8a8c
Revises: 66437892ff1a
Create Date: 2022-11-23 15:35:30.279138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a172f54a8a8c'
down_revision = '66437892ff1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('on_test', sa.Boolean(), nullable=True))
    op.drop_column('level', 'on_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('on_test', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('course', 'on_test')
    # ### end Alembic commands ###
