"""empty message

Revision ID: ad285eac0f4b
Revises: 06c430d07ab3
Create Date: 2022-11-11 15:30:41.321410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad285eac0f4b'
down_revision = '06c430d07ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('fk_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'language', 'session', ['fk_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'language', type_='foreignkey')
    op.drop_column('language', 'fk_session_id')
    # ### end Alembic commands ###
