"""empty message

Revision ID: b2031df34953
Revises: ad285eac0f4b
Create Date: 2022-11-11 15:31:23.972894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2031df34953'
down_revision = 'ad285eac0f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language_level', sa.Column('fk_level_id', sa.Integer(), nullable=True))
    op.add_column('language_level', sa.Column('fk_language_id', sa.Integer(), nullable=True))
    op.drop_constraint('language_level_language_id_fkey', 'language_level', type_='foreignkey')
    op.drop_constraint('language_level_level_id_fkey', 'language_level', type_='foreignkey')
    op.create_foreign_key(None, 'language_level', 'level', ['fk_level_id'], ['id'])
    op.create_foreign_key(None, 'language_level', 'language', ['fk_language_id'], ['id'])
    op.drop_column('language_level', 'level_id')
    op.drop_column('language_level', 'language_id')
    op.add_column('note', sa.Column('fk_level_id', sa.Integer(), nullable=True))
    op.add_column('note', sa.Column('fk_language_id', sa.Integer(), nullable=True))
    op.drop_constraint('note_level_id_fkey', 'note', type_='foreignkey')
    op.drop_constraint('note_language_id_fkey', 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'language', ['fk_language_id'], ['id'])
    op.create_foreign_key(None, 'note', 'level', ['fk_level_id'], ['id'])
    op.drop_column('note', 'level_id')
    op.drop_column('note', 'language_id')
    op.add_column('subscription', sa.Column('fk_student_id', sa.Integer(), nullable=True))
    op.add_column('subscription', sa.Column('fk_session_id', sa.Integer(), nullable=True))
    op.drop_constraint('subscription_session_id_fkey', 'subscription', type_='foreignkey')
    op.drop_constraint('subscription_student_id_fkey', 'subscription', type_='foreignkey')
    op.create_foreign_key(None, 'subscription', 'session', ['fk_session_id'], ['id'])
    op.create_foreign_key(None, 'subscription', 'user', ['fk_student_id'], ['id'])
    op.drop_column('subscription', 'session_id')
    op.drop_column('subscription', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.create_foreign_key('subscription_student_id_fkey', 'subscription', 'user', ['student_id'], ['id'])
    op.create_foreign_key('subscription_session_id_fkey', 'subscription', 'session', ['session_id'], ['id'])
    op.drop_column('subscription', 'fk_session_id')
    op.drop_column('subscription', 'fk_student_id')
    op.add_column('note', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('note', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key('note_language_id_fkey', 'note', 'language', ['language_id'], ['id'])
    op.create_foreign_key('note_level_id_fkey', 'note', 'level', ['level_id'], ['id'])
    op.drop_column('note', 'fk_language_id')
    op.drop_column('note', 'fk_level_id')
    op.add_column('language_level', sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('language_level', sa.Column('level_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'language_level', type_='foreignkey')
    op.drop_constraint(None, 'language_level', type_='foreignkey')
    op.create_foreign_key('language_level_level_id_fkey', 'language_level', 'level', ['level_id'], ['id'])
    op.create_foreign_key('language_level_language_id_fkey', 'language_level', 'language', ['language_id'], ['id'])
    op.drop_column('language_level', 'fk_language_id')
    op.drop_column('language_level', 'fk_level_id')
    # ### end Alembic commands ###
